import type { Category, Product } from "./types";

/**
 * Built-in catalog. Used when Supabase isn't configured yet (instant local
 * preview) and mirrored by supabase/seed.sql for the real database.
 */

export const fallbackCategories: Category[] = [
  { id: "cat-paintings", slug: "paintings", nameEn: "Paintings & Prints", nameEs: "Pinturas y láminas", sort: 1 },
  { id: "cat-clothing", slug: "clothing", nameEn: "Wearable Art", nameEs: "Arte para vestir", sort: 2 },
];

const p = (n: number) => n * 100;

function img(slug: string, count: number): string[] {
  return Array.from({ length: count }, (_, i) => `/products/${slug}/${i + 1}.jpg`);
}

export const fallbackProducts: Product[] = [
  {
    id: "prod-the-cockatoo",
    slug: "the-cockatoo",
    categorySlug: "paintings",
    nameEn: "The Cockatoo — Original Painting",
    nameEs: "La Cacatúa — Pintura original",
    descriptionEn:
      "A storm-blue cockatoo buried in a jungle of leaves and blossoms. This is the original, one-of-one acrylic painting on canvas — the loudest quiet companion your living room will ever have.",
    descriptionEs:
      "Una cacatúa azul tormenta escondida en una selva de hojas y flores. Esta es la pintura original, única, en acrílico sobre lienzo — la compañía silenciosa más ruidosa que tendrá tu salón.",
    detailsEn: "Original acrylic on canvas · 120 × 150 cm · signed by Magda · ships rolled in a protective tube",
    detailsEs: "Acrílico original sobre lienzo · 120 × 150 cm · firmado por Magda · se envía enrollado en tubo protector",
    priceCents: p(1450),
    compareAtCents: null,
    badge: "new",
    images: img("the-cockatoo", 1),
    sizes: null,
    stock: 1,
    isActive: true,
  },
  {
    id: "prod-parrots-in-love",
    slug: "parrots-in-love",
    categorySlug: "paintings",
    nameEn: "Parrots in Love — Original Painting",
    nameEs: "Loros enamorados — Pintura original",
    descriptionEn:
      "Two fire-orange parrots leaning into each other on a tangle of tropical color. Original acrylic on canvas, painted over three mad weeks.",
    descriptionEs:
      "Dos loros naranja fuego apoyados el uno en el otro sobre una maraña de color tropical. Acrílico original sobre lienzo, pintado durante tres semanas de locura.",
    detailsEn: "Original acrylic on canvas · 140 × 160 cm · signed by Magda · ships rolled in a protective tube",
    detailsEs: "Acrílico original sobre lienzo · 140 × 160 cm · firmado por Magda · se envía enrollado en tubo protector",
    priceCents: p(1600),
    compareAtCents: null,
    badge: "bestseller",
    images: img("parrots-in-love", 3),
    sizes: null,
    stock: 1,
    isActive: true,
  },
  {
    id: "prod-the-monkey-king",
    slug: "the-monkey-king",
    categorySlug: "paintings",
    nameEn: "The Monkey King — Art Print",
    nameEs: "El Rey Mono — Lámina",
    descriptionEn:
      "A screaming psychedelic monkey crowned in candy colors. Museum-grade giclée print of Magda's original painting.",
    descriptionEs:
      "Un mono psicodélico gritando, coronado en colores caramelo. Lámina giclée de calidad de museo de la pintura original de Magda.",
    detailsEn: "Giclée print · A3 (29.7 × 42 cm) · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · A3 (29,7 × 42 cm) · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("the-monkey-king", 2),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-st-pigeon",
    slug: "st-pigeon",
    categorySlug: "paintings",
    nameEn: "St. Pigeon — Art Print",
    nameEs: "San Palomo — Lámina",
    descriptionEn:
      "The patron saint of park benches, haloed in flames and roses. A tongue-in-cheek icon for people who take joy seriously.",
    descriptionEs:
      "El santo patrón de los bancos del parque, con un halo de llamas y rosas. Un icono con guiño para gente que se toma la alegría en serio.",
    detailsEn: "Giclée print · A3 (29.7 × 42 cm) · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · A3 (29,7 × 42 cm) · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: "bestseller",
    images: img("st-pigeon", 2),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-golden-cobra",
    slug: "golden-cobra",
    categorySlug: "paintings",
    nameEn: "Golden Cobra — Art Print",
    nameEs: "Cobra dorada — Lámina",
    descriptionEn:
      "A cobra in gold and venom-green, coiled like a warning and a welcome at the same time.",
    descriptionEs:
      "Una cobra en dorado y verde veneno, enroscada como advertencia y bienvenida a la vez.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("golden-cobra", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-the-tempest",
    slug: "the-tempest",
    categorySlug: "paintings",
    nameEn: "The Tempest (Puma) — Art Print",
    nameEs: "La Tempestad (Puma) — Lámina",
    descriptionEn:
      "A puma mid-storm, all muscle and static electricity. From the Humdrum series — for rooms that need a pulse.",
    descriptionEs:
      "Un puma en plena tormenta, todo músculo y electricidad estática. De la serie Humdrum — para habitaciones que necesitan pulso.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(110),
    compareAtCents: null,
    badge: null,
    images: img("the-tempest", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-neba-tiger",
    slug: "neba-tiger",
    categorySlug: "paintings",
    nameEn: "Neba Tiger — Art Print",
    nameEs: "Tigre Neba — Lámina",
    descriptionEn:
      "A tiger that swallowed a sunset. Layered stripes, impossible colors, zero apologies.",
    descriptionEs:
      "Un tigre que se tragó un atardecer. Rayas en capas, colores imposibles, cero disculpas.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(110),
    compareAtCents: null,
    badge: null,
    images: img("neba-tiger", 3),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-the-heron",
    slug: "the-heron",
    categorySlug: "paintings",
    nameEn: "The Heron — Art Print",
    nameEs: "La Garza — Lámina",
    descriptionEn:
      "A heron standing perfectly still while the jungle riots around it. For people who stay calm in loud rooms.",
    descriptionEs:
      "Una garza perfectamente quieta mientras la selva se alborota a su alrededor. Para gente que mantiene la calma en habitaciones ruidosas.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: "restocked",
    images: img("the-heron", 2),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-cat-eye",
    slug: "cat-eye",
    categorySlug: "paintings",
    nameEn: "Cat Eye — Art Print",
    nameEs: "Ojo de gato — Lámina",
    descriptionEn:
      "One enormous, knowing cat eye. It has seen your browser history and loves you anyway.",
    descriptionEs:
      "Un enorme ojo de gato que lo sabe todo. Ha visto tu historial y aun así te quiere.",
    detailsEn: "Giclée print · A3 (29.7 × 42 cm) · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · A3 (29,7 × 42 cm) · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(85),
    compareAtCents: null,
    badge: null,
    images: img("cat-eye", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-mirrors",
    slug: "mirrors",
    categorySlug: "paintings",
    nameEn: "Mirrors — Art Print",
    nameEs: "Espejos — Lámina",
    descriptionEn:
      "Reflections folding into reflections — a dreamscape from the Humdrum series that rewards long stares.",
    descriptionEs:
      "Reflejos que se pliegan en reflejos — un paisaje onírico de la serie Humdrum que premia las miradas largas.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("mirrors", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-the-bridge",
    slug: "the-bridge",
    categorySlug: "paintings",
    nameEn: "The Bridge — Art Print",
    nameEs: "El Puente — Lámina",
    descriptionEn:
      "A bridge between two worlds that don't quite agree on physics. Cross at your own delight.",
    descriptionEs:
      "Un puente entre dos mundos que no se ponen de acuerdo en la física. Crúzalo bajo tu propio deleite.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("the-bridge", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-weird-boy",
    slug: "weird-boy",
    categorySlug: "paintings",
    nameEn: "Weird Boy (Humdrum V) — Art Print",
    nameEs: "Chico raro (Humdrum V) — Lámina",
    descriptionEn:
      "The fifth chapter of the Humdrum series: a portrait of every kid who drew on the walls and turned out great.",
    descriptionEs:
      "El quinto capítulo de la serie Humdrum: un retrato de todos los niños que dibujaban en las paredes y acabaron geniales.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("weird-boy", 2),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-yolo-cat",
    slug: "yolo-cat",
    categorySlug: "paintings",
    nameEn: "YOLO Cat — Mini Print",
    nameEs: "Gato YOLO — Mini lámina",
    descriptionEn:
      "A spotted yellow cat diving through a hula hoop, because you only live once — nine times.",
    descriptionEs:
      "Un gato amarillo con manchas saltando por un aro, porque solo se vive una vez — nueve veces.",
    detailsEn: "Giclée print · A4 (21 × 29.7 cm) · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · A4 (21 × 29,7 cm) · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(75),
    compareAtCents: p(90),
    badge: "new",
    images: img("yolo-cat", 2),
    sizes: null,
    stock: 30,
    isActive: true,
  },
  {
    id: "prod-superius",
    slug: "superius",
    categorySlug: "paintings",
    nameEn: "Superius (Humdrum III) — Art Print",
    nameEs: "Superius (Humdrum III) — Lámina",
    descriptionEn:
      "Part three of the Humdrum series — a triumphant, over-caffeinated fever dream in full color.",
    descriptionEs:
      "Tercera parte de la serie Humdrum — un sueño febril triunfante y con demasiada cafeína, a todo color.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("superius", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-medicine",
    slug: "medicine",
    categorySlug: "paintings",
    nameEn: "Medicine (Humdrum IV) — Art Print",
    nameEs: "Medicina (Humdrum IV) — Lámina",
    descriptionEn:
      "The fourth Humdrum: strange remedies, bright bottles, and the suspicion that color heals faster than pills.",
    descriptionEs:
      "El cuarto Humdrum: remedios extraños, frascos brillantes y la sospecha de que el color cura más rápido que las pastillas.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("medicine", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-the-rooster",
    slug: "the-rooster",
    categorySlug: "paintings",
    nameEn: "The Rooster (Humdrum XVI) — Art Print",
    nameEs: "El Gallo (Humdrum XVI) — Lámina",
    descriptionEn:
      "A rooster with main-character energy. Crows at dawn, at noon, and whenever it feels underappreciated.",
    descriptionEs:
      "Un gallo con energía de protagonista. Canta al amanecer, al mediodía y cuando se siente poco valorado.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("the-rooster", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-mustard-cat",
    slug: "mustard-cat",
    categorySlug: "paintings",
    nameEn: "Mustard Cat (Humdrum XVII) — Art Print",
    nameEs: "Gato Mostaza (Humdrum XVII) — Lámina",
    descriptionEn:
      "A mustard-yellow cat with the confidence of a much larger animal. Seventeenth in the Humdrum series.",
    descriptionEs:
      "Un gato amarillo mostaza con la confianza de un animal mucho más grande. Decimoséptimo de la serie Humdrum.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: "new",
    images: img("mustard-cat", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-humdrum-vii",
    slug: "humdrum-vii",
    categorySlug: "paintings",
    nameEn: "Humdrum VII — Art Print",
    nameEs: "Humdrum VII — Lámina",
    descriptionEn:
      "The seventh Humdrum — a kaleidoscope of creatures that only makes more sense the longer you look.",
    descriptionEs:
      "El séptimo Humdrum — un caleidoscopio de criaturas que tiene más sentido cuanto más lo miras.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(95),
    compareAtCents: null,
    badge: null,
    images: img("humdrum-vii", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },
  {
    id: "prod-jacket-tiger",
    slug: "jacket-tiger",
    categorySlug: "paintings",
    nameEn: "Jacket Tiger — Art Print",
    nameEs: "Tigre con chaqueta — Lámina",
    descriptionEn:
      "A tiger in a very good jacket. Better dressed than most of us, and it knows it.",
    descriptionEs:
      "Un tigre con una chaqueta muy buena. Mejor vestido que la mayoría de nosotros, y lo sabe.",
    detailsEn: "Giclée print · 50 × 70 cm · 250 gsm archival matte paper · frame not included",
    detailsEs: "Lámina giclée · 50 × 70 cm · papel mate de archivo 250 g/m² · marco no incluido",
    priceCents: p(120),
    compareAtCents: p(150),
    badge: null,
    images: img("jacket-tiger", 1),
    sizes: null,
    stock: 25,
    isActive: true,
  },

  // ---- Clothing ----
  {
    id: "prod-kimono-blue-ginkgo",
    slug: "kimono-blue-ginkgo",
    categorySlug: "clothing",
    nameEn: "Blue Ginkgo Kimono",
    nameEs: "Kimono Ginkgo Azul",
    descriptionEn:
      "Cobalt blue meets poppy red in a ginkgo-leaf pattern painted by Magda and printed on flowing fabric. Throw it over anything and the room changes temperature.",
    descriptionEs:
      "El azul cobalto se encuentra con el rojo amapola en un patrón de hojas de ginkgo pintado por Magda e impreso en tela fluida. Póntelo sobre cualquier cosa y la habitación cambia de temperatura.",
    detailsEn: "100% viscose · relaxed one-size fit (fits US 4–14) · pattern from an original painting · gentle wash, cold",
    detailsEs: "100% viscosa · talla única holgada (equivale a US 4–14) · patrón de una pintura original · lavado suave, en frío",
    priceCents: p(145),
    compareAtCents: null,
    badge: "bestseller",
    images: img("kimono-blue-ginkgo", 5),
    sizes: ["One Size"],
    stock: 8,
    isActive: true,
  },
  {
    id: "prod-kimono-crane",
    slug: "kimono-crane",
    categorySlug: "clothing",
    nameEn: "The Crane Kimono",
    nameEs: "Kimono La Grulla",
    descriptionEn:
      "Sunshine yellow with teal jungle panels and crane motifs lifted straight from Magda's canvas. The piece people will ask you about at parties.",
    descriptionEs:
      "Amarillo sol con paneles de selva turquesa y motivos de grullas sacados directamente del lienzo de Magda. La prenda por la que te preguntarán en las fiestas.",
    detailsEn: "100% viscose · relaxed one-size fit (fits US 4–14) · pattern from an original painting · gentle wash, cold",
    detailsEs: "100% viscosa · talla única holgada (equivale a US 4–14) · patrón de una pintura original · lavado suave, en frío",
    priceCents: p(145),
    compareAtCents: null,
    badge: "new",
    images: img("kimono-crane", 5),
    sizes: ["One Size"],
    stock: 8,
    isActive: true,
  },
  {
    id: "prod-kimono-parrot",
    slug: "kimono-parrot",
    categorySlug: "clothing",
    nameEn: "The Parrot Kimono",
    nameEs: "Kimono El Loro",
    descriptionEn:
      "A riot of parrots, blossoms and zebra stripes on soft flowing fabric. Wearable proof that more is more.",
    descriptionEs:
      "Un alboroto de loros, flores y rayas de cebra sobre tela suave y fluida. Prueba ponible de que más es más.",
    detailsEn: "100% viscose · relaxed one-size fit (fits US 4–14) · pattern from an original painting · gentle wash, cold",
    detailsEs: "100% viscosa · talla única holgada (equivale a US 4–14) · patrón de una pintura original · lavado suave, en frío",
    priceCents: p(145),
    compareAtCents: null,
    badge: null,
    images: img("kimono-parrot", 5),
    sizes: ["One Size"],
    stock: 8,
    isActive: true,
  },
  {
    id: "prod-jungle-heart-tee",
    slug: "jungle-heart-tee",
    categorySlug: "clothing",
    nameEn: "Jungle Heart Tee",
    nameEs: "Camiseta Corazón de Selva",
    descriptionEn:
      "An oversized tee covered in Magda's jungle-heart pattern — orange, violet and green having the time of their lives. Unisex, heavyweight, zero chill.",
    descriptionEs:
      "Una camiseta oversize cubierta con el patrón corazón de selva de Magda — naranja, violeta y verde pasándolo en grande. Unisex, gruesa, cero discreción.",
    detailsEn: "100% combed cotton, 220 gsm · unisex oversized fit · pattern from an original painting · machine wash cold, inside out",
    detailsEs: "100% algodón peinado, 220 g/m² · corte unisex oversize · patrón de una pintura original · lavar en frío, del revés",
    priceCents: p(58),
    compareAtCents: null,
    badge: null,
    images: img("jungle-heart-tee", 5),
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 40,
    isActive: true,
  },
];
